version: '3.8'

services:
  # postgres:
  #   build:
  #     context: .
  #     dockerfile: ./deployment/dockerfile/postgres.Dockerfile
  #   container_name: gsm_postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: gsm_dev
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./deployment/config/db:/docker-entrypoint-initdb.d/
  #   # The line below will ensure SQL files are executed in alphabetical order
  #   command: ["postgres", "-c", "log_statement=all"]
  redis:
    build:
      context: .
      dockerfile: ./deployment/dockerfile/redis.Dockerfile
    container_name: gsm_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./deployment/config/redis/init.config:/usr/local/etc/redis/init.conf
    command: ["redis-server", "/usr/local/etc/redis/init.conf"]
  # mongo:
  #   build:
  #     context: .
  #     dockerfile: ./deployment/dockerfile/mongodb.Dockerfile
  #   container_name: gsm_mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo_data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongouser
  #     MONGO_INITDB_ROOT_PASSWORD: mongopw
  # minio:
  #   build:
  #     context: .
  #     dockerfile: ./deployment/dockerfile/minio.Dockerfile
  #   container_name: gsm_minio
  #   environment:
  #     MINIO_ROOT_USER: miniouser
  #     MINIO_ROOT_PASSWORD: miniosecret
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001" # for MinIO console
  #   volumes:
  #     - minio_data:/data
  #   command: server /data --console-address ":9001"
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./deployment/dockerfile/nginx.Dockerfile
  #   container_name: gsm_nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./deployment/config/nginx/nginx.config:/etc/nginx/nginx.config
  #     - ./web:/usr/share/nginx/html  # Map the frontend build(web) directory
  #   links:
  #     - account
  #     - realtime
  #   depends_on:
  #     - account
  #     - realtime
  # account:
  #   build:
  #     context: .
  #     dockerfile: ./deployment/dockerfile/account.Dockerfile
  #   container_name: gsm_account
  #   ports:
  #     - "8080:8080"
  #   command: ["/go/bin/account"]
  # realtime:
  #   build:
  #     context: .
  #     dockerfile: ./deployment/dockerfile/realtime.Dockerfile
  #   container_name: gsm_realtime
  #   ports:
  #     - "8081:8081"
  #   command: ["/go/bin/realtime"]

volumes:
  # postgres_data:
  # mongo_data:
  redis_data:
  # minio_data:
